### ISSUE TITLE
[BUG] push being rejected on Heroku

### ISSUE THREAD

**Issue by NeimadTL** [jamesstonehill/anonymous#8]
@jamesstonehill, I'm using rails 6.0.3, Ruby 2.7.2  and when trying to deploy on Heroku staging environment I'm getting the error below. Any idea on why this is happening please ? Any help would be much appreciated, thank you.
```
NameError: uninitialized constant User (call 'User.connection' to establish a connection)::Anonymous
       /tmp/build_21dd28c1_/app/models/user.rb:7:in `<class:User>'
       /tmp/build_21dd28c1_/app/models/user.rb:4:in `<main>'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/inflector/methods.rb:282:in `const_get'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/inflector/methods.rb:282:in `block in constantize'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/inflector/methods.rb:280:in `each'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/inflector/methods.rb:280:in `inject'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/inflector/methods.rb:280:in `constantize'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies/zeitwerk_integration.rb:19:in `constantize'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/bundler/gems/devise-92facc7f2b4a/lib/devise.rb:320:in `get'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/bundler/gems/devise-92facc7f2b4a/lib/devise/mapping.rb:83:in `to'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/bundler/gems/devise-92facc7f2b4a/lib/devise/mapping.rb:78:in `modules'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/bundler/gems/devise-92facc7f2b4a/lib/devise/mapping.rb:95:in `routes'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/bundler/gems/devise-92facc7f2b4a/lib/devise/mapping.rb:158:in `default_used_route'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/bundler/gems/devise-92facc7f2b4a/lib/devise/mapping.rb:72:in `initialize'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/bundler/gems/devise-92facc7f2b4a/lib/devise.rb:350:in `new'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/bundler/gems/devise-92facc7f2b4a/lib/devise.rb:350:in `add_mapping'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/bundler/gems/devise-92facc7f2b4a/lib/devise/rails/routes.rb:243:in `block in devise_for'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/bundler/gems/devise-92facc7f2b4a/lib/devise/rails/routes.rb:242:in `each'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/bundler/gems/devise-92facc7f2b4a/lib/devise/rails/routes.rb:242:in `devise_for'
       /tmp/build_21dd28c1_/config/routes.rb:5:in `block in <main>'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.4/lib/action_dispatch/routing/route_set.rb:426:in `instance_exec'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.4/lib/action_dispatch/routing/route_set.rb:426:in `eval_block'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.4/lib/action_dispatch/routing/route_set.rb:408:in `draw'
       /tmp/build_21dd28c1_/config/routes.rb:4:in `<main>'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:40:in `each'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:40:in `load_paths'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:20:in `reload!'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:29:in `block in updater'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/file_update_checker.rb:83:in `execute'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/application/routes_reloader.rb:10:in `execute'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/application/finisher.rb:184:in `block in <module:Finisher>'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `instance_exec'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `run'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:60:in `run_initializers'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/application.rb:363:in `initialize!'
       /tmp/build_21dd28c1_/config/environment.rb:7:in `<main>'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/application.rb:339:in `require_environment!'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/application.rb:523:in `block in run_tasks_blocks'
       /tmp/build_21dd28c1_/vendor/bundle/ruby/2.7.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by jamesstonehill** [comment]
Can you send me your `User` class file?

**Comment by NeimadTL** [comment]
I eventually fixed the issue. The gem declaration was in the `group :development, :test do` scope in gemfile.  That's why it couldn't be deployed.
